# Generated by Django.
# This file populates the database with sample data for 'alice' and 'bob'.
# Place this file in finance/migrations/0002_add_sample_data.py

from django.db import migrations
from django.contrib.auth.hashers import make_password
import datetime
from decimal import Decimal

def create_sample_data(apps, schema_editor):
    """
    Create sample users, accounts, categories, transactions, and budgets.
    """
    # Get models from the historical app registry
    User = apps.get_model('auth', 'User')
    Account = apps.get_model('finance', 'Account')
    Category = apps.get_model('finance', 'Category')
    Transaction = apps.get_model('finance', 'Transaction')
    Budget = apps.get_model('finance', 'Budget')

    # --- 1. Create Users ---
    # We use User.objects.create() here.
    # In a real scenario, create_user() is better, but this works in migrations.
    # A simple, known password for testing.
    hashed_password = make_password('password123')

    alice, _ = User.objects.get_or_create(
        username='alice',
        defaults={
            'password': hashed_password,
            'email': 'alice@example.com',
            'first_name': 'Alice',
            'last_name': 'Smith',
            'is_staff': True,
            'is_superuser': True
        }
    )

    bob, _ = User.objects.get_or_create(
        username='bob',
        defaults={
            'password': hashed_password,
            'email': 'bob@example.com',
            'first_name': 'Bob',
            'last_name': 'Johnson'
        }
    )

    # --- 2. Create Data for Alice (user_id = 1) ---
    
    # Alice's Accounts
    # We must manually set balances, as model's save() method is not called.
    alice_checking, _ = Account.objects.get_or_create(
        user=alice, name='Main Checking',
        defaults={'type': 'CHECKING', 'current_balance': 0}
    )
    alice_savings, _ = Account.objects.get_or_create(
        user=alice, name='Primary Savings',
        defaults={'type': 'SAVINGS', 'current_balance': 0}
    )
    alice_visa, _ = Account.objects.get_or_create(
        user=alice, name='Visa Card',
        defaults={'type': 'CREDIT_CARD', 'current_balance': 0}
    )

    # Alice's Categories
    cat_salary, _ = Category.objects.get_or_create(user=alice, name='Salary', type='INCOME')
    cat_freelance, _ = Category.objects.get_or_create(user=alice, name='Freelance', type='INCOME')
    cat_groceries, _ = Category.objects.get_or_create(user=alice, name='Groceries', type='EXPENSE')
    cat_rent, _ = Category.objects.get_or_create(user=alice, name='Rent', type='EXPENSE')
    cat_utilities, _ = Category.objects.get_or_create(user=alice, name='Utilities', type='EXPENSE')
    cat_restaurants, _ = Category.objects.get_or_create(user=alice, name='Restaurants', type='EXPENSE')

    # Alice's Transactions
    # We create transactions AND manually update account balances.
    
    # Salary
    Transaction.objects.get_or_create(
        user=alice, account=alice_checking, category=cat_salary,
        amount=Decimal('5000.00'), date=datetime.date(2025, 11, 1),
        type='INCOME', description='Monthly Salary'
    )
    alice_checking.current_balance += Decimal('5000.00')

    # Rent
    Transaction.objects.get_or_create(
        user=alice, account=alice_checking, category=cat_rent,
        amount=Decimal('1200.00'), date=datetime.date(2025, 11, 1),
        type='EXPENSE', description='Monthly Rent'
    )
    alice_checking.current_balance -= Decimal('1200.00')

    # Groceries
    Transaction.objects.get_or_create(
        user=alice, account=alice_visa, category=cat_groceries,
        amount=Decimal('75.50'), date=datetime.date(2025, 11, 3),
        type='EXPENSE', description='Grocery Run'
    )
    alice_visa.current_balance -= Decimal('75.50') # Credit card balance goes down (more negative)

    # Dinner
    Transaction.objects.get_or_create(
        user=alice, account=alice_visa, category=cat_restaurants,
        amount=Decimal('42.00'), date=datetime.date(2025, 11, 4),
        type='EXPENSE', description='Dinner with friends'
    )
    alice_visa.current_balance -= Decimal('42.00')

    # Electric Bill
    Transaction.objects.get_or_create(
        user=alice, account=alice_checking, category=cat_utilities,
        amount=Decimal('150.00'), date=datetime.date(2025, 11, 5),
        type='EXPENSE', description='Electric Bill'
    )
    alice_checking.current_balance -= Decimal('150.00')

    # Freelance Project
    Transaction.objects.get_or_create(
        user=alice, account=alice_savings, category=cat_freelance,
        amount=Decimal('300.00'), date=datetime.date(2025, 11, 7),
        type='INCOME', description='Freelance Project'
    )
    alice_savings.current_balance += Decimal('300.00')

    # Save final balances
    alice_checking.save()
    alice_savings.save()
    alice_visa.save()

    # Alice's Budgets
    Budget.objects.get_or_create(
        user=alice, category=cat_groceries,
        start_date=datetime.date(2025, 11, 1),
        end_date=datetime.date(2025, 11, 30),
        defaults={'amount': Decimal('500.00')}
    )
    Budget.objects.get_or_create(
        user=alice, category=cat_restaurants,
        start_date=datetime.date(2025, 11, 1),
        end_date=datetime.date(2025, 11, 30),
        defaults={'amount': Decimal('150.00')}
    )
    
    # --- 3. Create Data for Bob (user_id = 2) ---
    bob_checking, _ = Account.objects.get_or_create(
        user=bob, name='BofA Checking',
        defaults={'type': 'CHECKING', 'current_balance': 2200.00}
    )
    cat_paycheck, _ = Category.objects.get_or_create(user=bob, name='Paycheck', type='INCOME')
    cat_mortgage, _ = Category.objects.get_or_create(user=bob, name='Mortgage', type='EXPENSE')
    
    # We can just set the balance and add a few transactions for history
    Transaction.objects.get_or_create(
        user=bob, account=bob_checking, category=cat_paycheck,
        amount=Decimal('4000.00'), date=datetime.date(2025, 11, 5),
        type='INCOME', description='Paycheck'
    )
    Transaction.objects.get_or_create(
        user=bob, account=bob_checking, category=cat_mortgage,
        amount=Decimal('1800.00'), date=datetime.date(2025, 11, 6),
        type='EXPENSE', description='Mortgage payment'
    )
    # Note: Bob's balance is pre-set, we're just adding history.


def delete_sample_data(apps, schema_editor):
    """
    Deletes the sample data.
    """
    User = apps.get_model('auth', 'User')
    
    # Deleting the users will cascade and delete all their related data
    User.objects.filter(username__in=['alice', 'bob']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'), # Depends on your first migration
        ('auth', '0001_initial'),     # Ensures User model is available
    ]

    operations = [
        migrations.RunPython(create_sample_data, delete_sample_data),
    ]