# Generated by Django 5.2.8 on 2025-11-14 13:41

from django.db import migrations

def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('finance', 'Profile')
    for user in User.objects.filter(profile__isnull=True):
        Profile.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_profile'),
    ]

    operations = [
        migrations.RunPython(create_profiles_for_existing_users),
    ]
